### ISSUE TITLE
(low-prio suggestion) OpenVisualCloud SVT-VP9/AV1

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1094]
New high performance Scalable Video VP9 encoder (with rather high CPU requirements): [OpenVisualCloud SVT-VP9](https://github.com/OpenVisualCloud/SVT-VP9)

> The Scalable Video Technology for VP9 Encoder (SVT-VP9 Encoder) is a VP9-compliant encoder library core. The SVT-VP9 Encoder development is a work-in-progress targeting performance levels applicable to both VOD and Live encoding/transcoding video applications.

Also mentioned at [FRESHports](https://www.freshports.org/multimedia/svt-vp9/) and in its [SVNweb](https://svnweb.freebsd.org/ports/head/multimedia/svt-vp9/) so I guess there are efforts to bring it into ffmpeg. May be postponed until there is official support.

Also, a similar AV1 project: [OpenVisualCloud SVT-AV1](https://github.com/OpenVisualCloud/SVT-AV1)

**Comment by 1480c1** [comment]
I think I tried seeing if I could build it in mingw64 when it got released, but it failed due to some obscure error. I'll see if it works again because it seems interesting.

**Comment by 1480c1** [comment]
Couple of problems off the bat with SVT-AV1, since it requires sse extension and avx, using the default CFlags will not allow it to compile. Next, their cmakelist files like to add /MP as a flag if it detects the system to be Windows due to the assumption of VS2017, however gcc doesn't have that as a flag, meaning you would have to patch it to remove any /MP from all of the cmakelist files.  And finally, mingw64 gcc has problems with avx extensions etc. As such, it probably is not possible unless we only allow it on computers with VS2017 installed.

**Comment by wiiaboo** [comment]
And that would be out-of-scope of the suite.

**Comment by 1480c1** [comment]
It does seem like some people over there are trying to get the encoders to work with mingw and make avx a non requirement, so this seems like a maybe in the future

**Comment by moisesmcardona** [comment]
This can be closed since SVT-AV1 has been added to the suite.

**Comment by moisesmcardona** [comment]
SVT-AV1 has been added to the suite. Next: SVT-VP9?

**Comment by 1480c1** [comment]
Sure.
