### ISSUE TITLE
rust problem on i686 host

### ISSUE THREAD

**Issue by ghost** [m-ab-s/media-autobuild_suite#1101]
While having setup this Win10 32bit Home VM and the compilation 32bit->32bit going through all fine now then 32bit host CC ->64bit target fails for ripgrep with what you see here in the screenshots. It seems while entereing the target->x64 loop on a i686/32bit host the whole rustup installation is destroyed somehow and nothing can be used anymore because all programs report "not compatible with the version of Windows you're running", no matter the target.

I'm not "usually" building under any i686/32bit host. Just reporting here that something apparently isn't right with the ["not two"](https://github.com/jb-alvarado/media-autobuild_suite/issues/915) rust installations?

![u](https://user-images.githubusercontent.com/26191502/52973407-4e2ebf00-33be-11e9-9c14-6a3862f495f6.PNG)

**Comment by wiiaboo** [comment]
Try installing it manually, replacing `${MSYSTEM_CARCH}` in the `--default-host=` parameter by `i686` and see if downloads the rust tools in 32-bit and then install the 64-bit toolchain afterwards and see if they both work.

I don't have any 32-bit VM around or actual time to test it myself.

**Comment by schmidthubert** [comment]
I already did that, and didn't help. Seems the toolchain/folder stable-x86_64-pc-windows-gnu is not created at all plus it's trying the wrong one then or something. But no big deal, VERY low prio this. Will check later, very little time this week on the evenings. I'll put everything in 2 separate scripts next and see what happens in every console then, and will try target 64bit only as well. A bit strange this. Thanks for your reply! :+1:

**Comment by schmidthubert** [comment]
Serveral mingw64 binaries are not working when on a i686 host, like curl for instance. That's why the x86_64 toolchain couldn't even be downloaded. I used wget to download but then there are other problems. So I suspect there will be more of such broken binaries. I'll check further if I can find some time, but will try without rust/ripgrep first to check which binaries that we use here are (not) working. The autogen.exe not working in mingw32 was one thing, but this is something else now.  =:-(

**Comment by wiiaboo** [comment]
Yeah, I'd just rather not support MSYS2 32-bit forever. If upstream doesn't use it or maintain it properly there's no point in trying to get old crap to work.
