### ISSUE TITLE
Download msys2 basic system failed

### ISSUE THREAD

**Issue by mrinawoo** [m-ab-s/media-autobuild_suite#1458]
I apologise if this is user error, I have no experience coding. I also couldn't find any log files, so all I have is these terminal errors. I tried manually adding msys myself from the link the script gave, but anything I put in the build folder is just ignored. Again, I apologise if this is my fault.

```
Do you want to run software from this untrusted publisher?
File C:\media_autobuild\build\pscx\TypeData\Pscx.SIUnits.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6
Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\media_autobuild\build\pscx\TypeData\Pscx.TerminalServices.Type.ps1xml is published by CN=6L6 Software LLC,
O=6L6 Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted
publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\media_autobuild\build\pscx\TypeData\Pscx.Reflection.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6
Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\media_autobuild\build\pscx\TypeData\Pscx.FeedStore.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6
Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\media_autobuild\build\pscx\TypeData\Pscx.Wmi.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software
LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\media_autobuild\build\pscx\TypeData\Pscx.Archive.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6
Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): Import-Module : The following error occurred while loading the extended type data file: ,
C:\media_autobuild\build\pscx\TypeData\Pscx.SIUnits.Type.ps1xml: The file was skipped because of the following
validation exception: AuthorizationManager check failed..
, C:\media_autobuild\build\pscx\TypeData\Pscx.TerminalServices.Type.ps1xml: The file was skipped because of the
following validation exception: AuthorizationManager check failed..
, C:\media_autobuild\build\pscx\TypeData\Pscx.Reflection.Type.ps1xml: The file was skipped because of the following
validation exception: AuthorizationManager check failed..
, C:\media_autobuild\build\pscx\TypeData\Pscx.FeedStore.Type.ps1xml: The file was skipped because of the following
validation exception: AuthorizationManager check failed..
, C:\media_autobuild\build\pscx\TypeData\Pscx.Wmi.Type.ps1xml: The file was skipped because of the following
validation exception: AuthorizationManager check failed..
, C:\media_autobuild\build\pscx\TypeData\Pscx.Archive.Type.ps1xml: The file was skipped because of the following
validation exception: AuthorizationManager check failed..
At line:1 char:18
+ ...             Import-Module $PWD\pscx\Pscx.psd1 -Force -Cmdlet Expand-A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Expand-7zaArchive : The term 'Expand-7zaArchive' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:111
+ ... Expand-Archive -Prefix 7za;                 Expand-7zaArchive -Force  ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-7zaArchive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Expand-7zaArchive : The term 'Expand-7zaArchive' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:242
+ ... tem $PWD\msys2-base.tar.xz;                 Expand-7zaArchive -Force  ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-7zaArchive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Remove-Item : Cannot find path 'C:\media_autobuild\build\msys2-base.tar' because it does not exist.
At line:1 char:333
+ ... $PWD\msys2-base.tar;                 Remove-Item $PWD\msys2-base.tar;
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\media_autobuild\build\msys2-base.tar:String) [Remove-Item], ItemNotF
   oundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by 1480c1** [comment]
Are you running behind an enterprise or similar firewall?

**Comment by mrinawoo** [comment]
No, I don't believe I am. All I have is Windows firewall, and disabling that didn't fix anything.

**Comment by Barough** [comment]
I've ran into the same issue also.

Do you want to run software from this untrusted publisher?
File D:\media-ab_suite\build\pscx\TypeData\Pscx.Archive.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software
 LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File D:\media-ab_suite\build\pscx\TypeData\Pscx.TerminalServices.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6
 Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File D:\media-ab_suite\build\pscx\TypeData\Pscx.Wmi.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software
LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File D:\media-ab_suite\build\pscx\TypeData\Pscx.Reflection.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6
Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File D:\media-ab_suite\build\pscx\TypeData\Pscx.SIUnits.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software
 LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File D:\media-ab_suite\build\pscx\TypeData\Pscx.FeedStore.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6
Software LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): Import-Module : The following error occurred while loading the extended type data file: , D:\media-ab_suite\build\pscx\
TypeData\Pscx.Archive.Type.ps1xml: The file was skipped because of the following validation exception: AuthorizationMan
ager check failed..
, D:\media-ab_suite\build\pscx\TypeData\Pscx.TerminalServices.Type.ps1xml: The file was skipped because of the followin
g validation exception: AuthorizationManager check failed..
, D:\media-ab_suite\build\pscx\TypeData\Pscx.Wmi.Type.ps1xml: The file was skipped because of the following validation
exception: AuthorizationManager check failed..
, D:\media-ab_suite\build\pscx\TypeData\Pscx.Reflection.Type.ps1xml: The file was skipped because of the following vali
dation exception: AuthorizationManager check failed..
, D:\media-ab_suite\build\pscx\TypeData\Pscx.SIUnits.Type.ps1xml: The file was skipped because of the following validat
ion exception: AuthorizationManager check failed..
, D:\media-ab_suite\build\pscx\TypeData\Pscx.FeedStore.Type.ps1xml: The file was skipped because of the following valid
ation exception: AuthorizationManager check failed..
At line:1 char:18
+ ...             Import-Module $PWD\pscx\Pscx.psd1 -Force -Cmdlet Expand-A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Expand-7zaArchive : The term 'Expand-7zaArchive' is not recognized as the name of a cmdlet, function, script file, or o
perable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try aga
in.
At line:1 char:111
+ ... Expand-Archive -Prefix 7za;                 Expand-7zaArchive -Force  ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-7zaArchive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Expand-7zaArchive : The term 'Expand-7zaArchive' is not recognized as the name of a cmdlet, function, script file, or o
perable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try aga
in.
At line:1 char:242
+ ... tem $PWD\msys2-base.tar.xz;                 Expand-7zaArchive -Force  ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-7zaArchive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Remove-Item : Cannot find path 'D:\media-ab_suite\build\msys2-base.tar' because it does not exist.
At line:1 char:333
+ ... $PWD\msys2-base.tar;                 Remove-Item $PWD\msys2-base.tar;
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\media-ab_suite\build\msys2-base.tar:String) [Remove-Item], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand



Only Windows Firewall here.

**Comment by 1480c1** [comment]
I see, I will try to see what's wrong

**Comment by deadsound** [comment]
Same Here....downloaded and paste uncompressed msys65 folder in build. Thanks!







Active code page: 65001
-------------------------------------------------------------------------------
                                                                                                                        - Download and install msys2 basic system                                                                                                                                                                                                       -------------------------------------------------------------------------------                                         -------------------------------------------------------------------------------

- Downloading and unpacking msys2 basic system

-------------------------------------------------------------------------------

Do you want to run software from this untrusted publisher?
File C:\mingw\build\pscx\TypeData\Pscx.Archive.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software LLC,
L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\mingw\build\pscx\TypeData\Pscx.FeedStore.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software LLC,
L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\mingw\build\pscx\TypeData\Pscx.TerminalServices.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software
 LLC, L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\mingw\build\pscx\TypeData\Pscx.Wmi.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software LLC, L=Fort
Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\mingw\build\pscx\TypeData\Pscx.SIUnits.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software LLC,
L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
Do you want to run software from this untrusted publisher?
File C:\mingw\build\pscx\TypeData\Pscx.Reflection.Type.ps1xml is published by CN=6L6 Software LLC, O=6L6 Software LLC,
L=Fort Collins, S=CO, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): Import-Module : The following error occurred while loading the extended type data file: ,
C:\mingw\build\pscx\TypeData\Pscx.Archive.Type.ps1xml: The file was skipped because of the following validation
exception: AuthorizationManager check failed..
, C:\mingw\build\pscx\TypeData\Pscx.FeedStore.Type.ps1xml: The file was skipped because of the following validation
exception: AuthorizationManager check failed..
, C:\mingw\build\pscx\TypeData\Pscx.TerminalServices.Type.ps1xml: The file was skipped because of the following
validation exception: AuthorizationManager check failed..
, C:\mingw\build\pscx\TypeData\Pscx.Wmi.Type.ps1xml: The file was skipped because of the following validation
exception: AuthorizationManager check failed..
, C:\mingw\build\pscx\TypeData\Pscx.SIUnits.Type.ps1xml: The file was skipped because of the following validation
exception: AuthorizationManager check failed..
, C:\mingw\build\pscx\TypeData\Pscx.Reflection.Type.ps1xml: The file was skipped because of the following validation
exception: AuthorizationManager check failed..
At line:1 char:18
+ ...             Import-Module $PWD\pscx\Pscx.psd1 -Force -Cmdlet Expand-A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Expand-7zaArchive : The term 'Expand-7zaArchive' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:111
+ ... Expand-Archive -Prefix 7za;                 Expand-7zaArchive -Force  ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-7zaArchive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Expand-7zaArchive : The term 'Expand-7zaArchive' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:242
+ ... tem $PWD\msys2-base.tar.xz;                 Expand-7zaArchive -Force  ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-7zaArchive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Remove-Item : Cannot find path 'C:\mingw\build\msys2-base.tar' because it does not exist.
At line:1 char:333
+ ... $PWD\msys2-base.tar;                 Remove-Item $PWD\msys2-base.tar;
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\mingw\build\msys2-base.tar:String) [Remove-Item], ItemNotFoundExcept
   ion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by Barough** [comment]
Managed now to get the script to continue/run after extracting the msys64 into the MABS folder. MSYS64 updates etc running now

**Comment by benjstern** [comment]
Same here, it looks like it terminates before it has a chance to finish downloading or at least fails on the extract, pasting the folders doesn't seem to help b/c it tries to write over it ... so it starts the download from 0. Even extracted it fails...

**Comment by PeterJohnson** [comment]
The problem is the code on line 1363 of the batch file.  Basically if you don't have a "7z" command installed, the script tries to install and use pscx to do the extraction, which requires trusting the pscx certificate (and setting the execution policy to allow running signed scripts).  I was able to workaround by downloading and extracting the pscx nuget package and running `import-module .\pscx.psd1 -cmdlet expand-archive -prefix 7za` from a PowerShell prompt and trusting "always".  An easier workaround might be simply to install 7zip so that 7z.exe is on the path.

**Comment by wiiaboo** [comment]
That's what the suite did before.

**Comment by benjstern** [comment]
@PeterJohnson Thanks, so adding 7zip to the environment variables seemed to fix it for me, what is strange is that i believe 7-zip used to give an option to add itself to the path automatically, though that might have been in the exe installer and i used the msi...

**Comment by shmediaproductions** [comment]
Doesn't seem to work for me, I already had 7zip installed and in path and it just goes right to trying to install pscx. I tried manually adding a specific "7z" variable directed at the 7z.exe binary but that didn't do anything. Idk if this is different from what you were experiencing. My log doesn't give any indication that it's looking for 7z, the very first message is about pscx

**Comment by shmediaproductions** [comment]
Actually I think mine was maybe an issue with windows update or something. My built-in powershell is up to date according to $PSVersionTable but for whatever reason when I just double click the script to open with that powershell binary, I get this problem. But if I instead start the windows terminal preview and load a powershell profile and manually run the script from there, no problems. It's a little weird because I was under the impression windows terminal does not use its own powershell binary, I think it uses the same GUID registered to the package that installs with windows. Anyway for whatever reason seems like powershell wasn't seeing my up to date path, and running powershell within windows terminal resolved that for whatever reason.
