### ISSUE TITLE
Help with build options for various use cases

### ISSUE THREAD

**Issue by kc6108** [m-ab-s/media-autobuild_suite#1538]
As part of my son's high school senior project, he needs to convert home media (home videos, hard media, etc) into different audio and video formats and then create backups. He needs a program to do the converting (one at a time or batch) and then another to play back the media with multi-user support. I've been helping him, and this suite seems to be perfect.

He needs to demonstrate an understanding of dynamic vs static through the various builds of ffmpeg and front-end programs.

For the offline conversion process, he believes a static build would be best. For playback of the content, he wants a dynamic build.

Setting up the build environment has been straight forward. He downloaded and installed VS 2017 (choosing the C++ option) as well as the CUDA toolkit. He just got a hand-me-down quad-core computer with a fresh install of Windows 10 Pro as well as a hand-me-down Nvidia 1050 Ti SC card. He also has an AMD card to work with too.

Now that it's time for building ffmpeg, what selections should he make for each build? We know (or think we know) the difference between a static build and a shared build using external libraries. Where does standalone fit in there? What programs would be best the best fit to achieve his goals? He will also need to perform some of these same tasks on Ubuntu (or Debian). We've been working on the build process for ffmpeg on a Synology NAS. It's going well. We got VAAPI and QSV to work, as well as, build dynamic and static builds.

This is only a small part of his project (believe it or not), but he wants help getting it out of the way.

We appreciate any help or advise.

**Comment by 1480c1** [comment]
I guess first off would be a recommendation to look at other forums for any general advice since this is probably not the best place to get general advice.

Next
> Now that it's time for building ffmpeg, what selections should he make for each build? ...

Does he only need ffmpeg? If so, then you can set standalone to no since that flag only triggers certain executables from encoders to be built (`aomenc.exe` from libaom for example).

I would probably look around FFmpeg's configure script (Particularly the help text) to see what you want to compile and what you don't need https://github.com/FFmpeg/FFmpeg/blob/master/configure
I personally recommend starting off with x264, x265, libaom, dav1d, libopus, flac, and if you aren't distributing the build or don't care about licensing, fdk-aac to start with. If you don't know what any of them means, I highly recommend taking the time and google searching each of them to understand why I'm listing them here.

Do remember that this suite will only provide the tools for video and audio encoding/decoding so our support here is limited to the suite and stuff directly related to the suite (so we don't really help with linux compiling, that would be best suited for a ffmpeg related forum like https://ffmpeg.zeranoe.com/forum/ or ffmpeg-user mailing list https://lists.ffmpeg.org/mailman/listinfo/ffmpeg-user/ , and other ways of contact https://ffmpeg.org/contact.html#Forums)

Next, this suite is primarily targeting static compilation with I guess best classified as second class support for shared compilation simply because of dependency issues that dynamic linking can cause on windows. We do not actively test if shared compilation is truly shared all the way through, if you do have an issue with it, you can always open a new issue about it.

Finally, it's probably best to be short, simple, and direct with what you are asking, since on places like github issues, we don't really need a story unless it's the steps to reproduce an issue. Either way, good luck to your son, if you do have any other questions, you can ask.

**Comment by kc6108** [comment]
We have already built scripts to compile ffmpeg on linux (one for a static build and then one for a dynamic build) . We have already converted some home movies that were recorded on our Sony HandyCam in AVC/AC3 to various other video and audio formats using both builds. We are all good there.

We will create a static build of ffmpeg, and a dynamic one using your script. All we will need to do is be able to convert the same home videos into various other formats... HEVC/Xvid/EAC3/AAC/FLAC just as we did on linux.

We believe we understand what the relationship between static/dynamic/standalone is now. Static is building ffmpeg (a bigger ffmpeg.exe in the end) with no external dependancies/files/DLLs (or much fewer), dynamic is building ffmpeg (a smaller ffmpeg.exe in the end) with lots of external dependancies/files/DLLs, and standalone is for outlier tools that can't be built dynamically... is this correct?

Static seems preferred in Windows, but in Linux it's not (due to the bigger size, ram usage, and for security reasons)... correct?

Are there any of the outlier tools, for example mpv or mplayer, that we can actually build and use to play the files we used ffmpeg to convert?

Thank you so much, we won't ask any more questions.

**Comment by 1480c1** [comment]
> No, he needs more than ffmpeg, such as x265 (HEVC), x264 (AVC), Xvid, fdk-aac, etc. He also needs QSV and CUDA/Nvidia stuff for his 1050 Ti SC graphics card.

I mean does he also need stuff like `x265.exe`, or is he just fine with `ffmpeg.exe` with `libx265` support so he can do `ffmpeg -i input.mp4 -c:v libx265 hevc.mp4`. Standable just triggers certain build configurations to build their separate executable along with their libs, or just only build their libs, static or not.

You are right on static building resulting into a bigger ffmpeg.exe, however, one thing to note about shared/dynamic is that although the executable will be smaller, the overall amount of space taken is about the same due to needing the dll files along with the exe file. Standalone option is separate from the static/dynamic part.

> Static seems preferred in Windows, but in Linux it's not (due to the bigger size, ram usage, and for security reasons)... correct?

Although in other parts of windows, dynamic dlls are prefered, I personally prefer static since it's easier to move the executables without needing to copy over the dlls if I want to use them on another machine. In linux, since there's an actual sane and common location to store shared libraries (`/usr/lib` or `/usr/local/lib`), it's much prefered to go with shared since that makes it so that there's only one copy of the code needed to run whenever a executable requests it and you can drop in replace the shared library without needing to recompile the executable everytime. Plus the extra decreased system size, decreased ram once loaded in, however, security isn't necessarily implied with shared.

One thing I recommend is to just compile ffmpeg on the conversion machine and compile mpv for use on the playback machine. Although ffmpeg+ffplay can handle playback, ffmpeg is mainly designed for converting, transcoding, and filtering audio and video from one format to another. mpv is a dedicated player for playback purposes, similar to vlc, however, in this case, we don't compile vlc with our libs, so if you want vlc, you would have to download that from their website. Other than that, no other recommendations for what you might need. Good luck

**Comment by kc6108** [comment]
This is the son. Thank you so much for all of your help. I have been researching how to build ffmpeg for a long time, and you have put so many missing pieces together for me. Last set of questions.
>I mean does he also need stuff like x265.exe, or is he just fine with ffmpeg.exe with libx265 support so he can do ffmpeg -i input.mp4 -c:v libx265 hevc.mp4. Standable just triggers certain build configurations to build their separate executable along with their libs, or just only build their libs, static or not.
>Standalone option is separate from the static/dynamic part.

So you are saying if I select `standalone` for `x265`, I will get a standalone executable (x265.exe), in addition to, the `x265` libs being either linked to ffmpeg as `shared` or `static` depending on how I chose to link it? I take it that standalone executable is completely portable as it doesn't need any outside dependencies (or if it did they would be built inside it), correct?

If I select `static`, the libs actually go into the `ffmpeg.exe`, correct?

If I select `dynamic` the libs (usually .so files on linux and DLLs? for Windows) live outside the executable and must be found in the PATH/RPATH, correct?

Hypothetical situation, I have a high-powered Windows server farm running a DLNA server on each that has to handle the transcoding of 25 (more or less) audio/video streams at any given time... would it be better to have a shared build of ffmpeg? That way the memory/ram footprint is smaller like on linux, or would we rather increase CPU/RAM to make up for that larger footprint?

**Comment by 1480c1** [comment]
> So you are saying if I select `standalone` for `x265`, I will get a standalone executable (x265.exe), in addition to, the `x265` libs being either linked to ffmpeg as `shared` or `static` depending on how I chose to link it? I take it that standalone executable is completely portable as it doesn't need any outside dependencies (or if it did they would be built inside it), correct?

Yes, you would be able to move `x265.exe` to another folder or machine an it should run fine (as long as the architecture is correct)



> If I select `static`, the libs actually go into the `ffmpeg.exe`, correct?

Yes



> If I select `dynamic` the libs (usually .so files on linux and DLLs? for Windows) live outside the executable and must be found in the PATH/RPATH, correct?

Yes, so you would need to copy the `.dll` files along with `ffmpeg.exe` to wherever you need. One thing I recommend you to learn about is the ldd tool, you can open mintty and type `ldd /local64/bin-video/ffmpeg.exe` and examine the output. The ones with `=> /c/WINDOWS...` you can ignore since they are system dlls, the ones you would need to worry about would be ones like
```none
libopenh264.dll => /trunk/local64/bin-video/libopenh264.dll
```
since those are not system dlls and you would need to copy those over

Here's microsoft's doc on dll search path https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications




> Hypothetical situation, I have a high-powered Windows server farm running a DLNA server on each that has to handle the transcoding of 25 (more or less) audio/video streams at any given time... would it be better to have a shared build of ffmpeg? That way the memory/ram footprint is smaller like on linux, or would we rather increase CPU/RAM to make up for that larger footprint?

If you are running multiple instances of ffmpeg, it would be better to build shared, with all else being equal, since that way the code will only need to be loaded into ram once for the entire time ffmpeg is using it. The only trade off in that case would be a slight increase in initial startup time since it would have to load the exe, then the dll file into ram. However, I recommend running some preliminary tests to see if that trade-off is worth it or if it's too miniscule to matter about.
