### ISSUE TITLE
Request: Can be VLC compiled together?

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1547]
Can be VLC compiled together?

**Comment by 1480c1** [comment]
Will depend on @wiiaboo  if this would be ok since we've predominantly have been building command line based tools. I personally would be fine with it

**Comment by dbyoung720** [comment]
I see

**Comment by wiiaboo** [comment]
Depends if adding vlc would not blatantly duplicate the suite's codesize.

It would be more useful than mplayer, at least.

**Comment by 1480c1** [comment]
I'll try to see if I can compile vlc with the suite successfully after I wait for the suite to pull mintty again.

If we add vlc, should we remove mplayer? Since we currently have 2(3?) available players, mpv, mplayer, and I guess ffplay.

I sort of wish we had an easy way to gather information of who's using what options like mplayer and ffmbc

**Comment by dbyoung720** [comment]
Under windows, the most commonly used is ffmpeg, followed by VLC.
MPV is a new one, and there are not many people using it. Of course, it is also very powerful.
Mplayer can hardly be used under windows, and few people use it.
