### ISSUE TITLE
vlc make a package

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1579]
vlc make a package, otherwise I don't know which files to copy out.

I support your attitude towards work and responsibility.
I can give a reward, a little bit.
Can consider turning on the reward function

**Comment by 1480c1** [comment]
I did try to do what vlc does when they package their executables, however, one problem I encountered is that their system assumes we are running a linux distro, and so we would first need to work on their side to fix those assumptions

**Comment by 1480c1** [comment]
Alternatively, I can make a `vlc` folder under the local** folder for vlc to install everything to

@wiiaboo, do you think that would be a good idea? Should it go under bin-video/vlc/ or something instead?

**Comment by dbyoung720** [comment]
In addition：
when compiling qt5(from x86 to x64), it is best to add: git.exe clean -d  -fx -f
clear the intermediate code from the last compilation

**Comment by 1480c1** [comment]
I did have that at one point, but I'm not sure why I removed it now

**Comment by dbyoung720** [comment]
QT5 x86 compiled intermediate code will affect x64 compilation,
QT5 x64 compilation will fail

**Comment by 1480c1** [comment]
I found out why, I didn't add an exclusion for the files the suite makes for tracking in the clean command, doing it right now.

**Comment by 1480c1** [comment]
Try again now

**Comment by dbyoung720** [comment]
ok

**Comment by wiiaboo** [comment]
> 
> 
> Alternatively, I can make a `vlc` folder under the local** folder for vlc to install everything to
> 
> @wiiaboo, do you think that would be a good idea? Should it go under bin-video/vlc/ or something instead?

Sure.

**Comment by 1480c1** [comment]
@wiiaboo I'm thinking it might be better to separate vlc into its repo under m-ab-s and make it based on mabs so you could just use the same folder and msys2. That way it would be easier to manage vlc's dependencies separate from the local* folders into their own `vlc-$bits` folders or something, because either way, I think I will need to have a separate compile of x264 for vlc since I can't play x264 videos with the vlc compiled. This also might be helpful since we already have a lot of projects being built in mabs.

To do this it might require separating a lot of the bat file etc similar to the helper.sh. Do you have any comments?

**Comment by wiiaboo** [comment]
That's a great idea. Low priority, of course, but it would help quarantine vlc-specific issues and work.
