### ISSUE TITLE
shaderc: scope issues for snprintf, may need explicit cstdio include for GCC 10.1

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1654]
Reported upstream to [Google shaderc issue 1065](https://github.com/google/shaderc/issues/1065)

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4633502/logs.zip)

I find it ... *entertaining* ... that the compiler suggests including `cstdio` in its error messages.

**Comment by LigH-de** [comment]
Comment by @106062316

> This is the line that causes the error
> https://github.com/KhronosGroup/glslang/blob/24dcbd1b1f68ff268bfa22dc4b72bec73d52abe7/glslang/Include/Common.h#L53
>
> If you removed the check for MINGW_HAS_SECURE_API in that header, the build will succeed.

**Comment by 1480c1** [comment]
I think they wanted GCC 10 to be more helpful in their error/warning messages

**Comment by 1480c1** [comment]
I'm assuming the reason why you have that error is that in the `Common.h`, they define a replacement of `sprintf` to `sprintf_s`, before including `cstdio` on https://github.com/KhronosGroup/glslang/blob/24dcbd1b1f68ff268bfa22dc4b72bec73d52abe7/glslang/Include/Common.h#L104

Thus replacing the declaration for `sprintf` from the regular stdio.h with a declaration for `sprintf_s`, which doesn't work since stdio.h has a regular C linkage, thus no overloading.

One fix  I can see is to move all of their preprocessing to after including the headers so that their defines will only affect the files that include `Common.h` instead of affecting the included system files too.
