### ISSUE TITLE
Getting rust.install failed - cargo-c-git 

### ISSUE THREAD

**Issue by ginishk** [m-ab-s/media-autobuild_suite#1707]
I am getting the following error while building 
rust.install failed. Check E:/../media-autobuild_suite-master/build/cargo-c-git/ab-suite.rust.install.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4769317/logs.zip)

 [logs.zip](https://0x0.st/iVRe.zip)

**Comment by 1480c1** [comment]
```none
error occurred: Command "ar" "crs" "E:\\Ginish\\RnD\\NineSixteen\\media-autobuild_suite-master\\build\\cargo-c-git\\target\\x86_64-pc-windows-gnu\\release\\build\\libgit2-sys-cef0a9e2189221c4\\out\\build\\libgit2.a" "E:\\Ginish\\RnD\\NineSixteen\\media-autobuild_suite-master\\build\\cargo-c-git\\target\\x86_64-pc-windows-gnu\\release\\build\\libgit2-sys-cef0a9e2189221c4\\out\\build\\libgit2/src\\alloc.o" ... "E:\\Ginish\\RnD\\NineSixteen\\media-autobuild_suite-master\\build\\cargo-c-git\\target\\x86_64-pc-windows-gnu\\release\\build\\libgit2-sys-cef0a9e2189221c4\\out\\build\\libgit2/src/hash/sha1/sha1dc/ubc_check.o" with args "ar" failed to start.
```

seems to me that cargo failed to build one of the dependents because it had too many arguments to `ar`

this is maybe a cargo issue and not something we can solve in the suite. One solution, if we had access to the direct commands, would be to instead run `ar` multiple times over a smaller grouping of `.o` files to make sure we do not exceed any max length on windows (currently around 15953 chars with the quotes and 15784 without the quotes). I do not know how exactly does cargo call external programs like `ar` since I haven't looked at their code, so I am entirely as clueless as you as to if they do exceed or don't, but that is my guess.

**Comment by ShinigamiBoss** [comment]
Hi, unfortunately I had the same issues.
Based on the information given by @1480c1 I solved the problem by simply moving the files to the root of the HDD. (In your case just move the media-autobuild_suite-master folder to E:/)
This result in shorter parameter path length and compiled successfully.
Hope this will help you too.

**Comment by wiiaboo** [comment]
Seems like [this](https://github.com/m-ab-s/media-autobuild_suite/blob/master/media-autobuild_suite.bat#L56) should be made even shorter.

**Comment by 1480c1** [comment]
```bash
$ printf '%s' "C:/media-autobuild_suite-master" | wc -c
31
```
wonder what number we should try. I guess the best way would be to try going from between 60 to 31

**Comment by ginishk** [comment]
i had disabled rav1e by commenting  #--enable-librav1e from ffmpeg_options.txt  as a work around. I will now try building as you guys suggested.
