### ISSUE TITLE
Request: [youtube-dl]

### ISSUE THREAD

**Issue by whiteinnocence** [m-ab-s/media-autobuild_suite#1790]
Hi,
would it be possible to include youtube dl?

Thank you very much in advance

**Comment by wiiaboo** [comment]
No, same reason as before: https://github.com/m-ab-s/media-autobuild_suite/issues/716

**Comment by wiiaboo** [comment]
If the ytdl devs don't release more frequently it's usually because master isn't stable enough to warrant a release, but they usually release quite frequently.

Adding this to the suite would just add an alternative compilation other than the official one for almost no gain at all and might lead to compilation-specific issues that are then hard to debug.
There's no options to choose, nothing that can be be optimized further by compiling it in the suite.

Either use the official releases (https://yt-dl.org/latest/youtube-dl.exe), or install Python 3.x and install it using `pip` and you'll be much better served than by the suite pooping out a likely broken .exe.
The suite would literally be downloading https://yt-dl.org/latest/youtube-dl.exe every time it changed.
