### ISSUE TITLE
Request: Windows 10 long path support

### ISSUE THREAD

**Issue by stax76** [m-ab-s/media-autobuild_suite#1806]
I would like to request Windows 10 long path support for:

aom
fdk-aac
ffmpeg
mp4box
mpv
rav1e
svt-av1
x264
x265

https://forum.doom9.org/showthread.php?t=181826

https://github.com/staxrip/staxrip/issues/338

**Comment by wiiaboo** [comment]
Did you try asking any of those libs' devs yet?
Unless it's some plug-and-play solution, there's really nothing we can do.

**Comment by stax76** [comment]
A list on what I asked is here:

https://github.com/staxrip/staxrip/issues/338

staxrip depends on like 20 tools that deal with paths, so far about 5 support it.

**Comment by 1480c1** [comment]
based on reading, there doesn't seem to be an easy way to generate the manifest needed for those tools, and the only info on how to generate it is through msvc's gui, other than handwriting them.

There doesn't seem to be anything mabs can do in general since I don't think it's worth our time trying to handwrite them for each and every project you have listed there. It would probably be better if you went to each individual project to try to request it, but even then, I'm not sure how all of them would be able to add a manifest file to their binaries.

**Comment by stax76** [comment]
I don't think it's necessary to generate a manifest because a generic manifest with completely identical content would work for all projects I believe:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
  <assemblyIdentity version="0.0.0.0" name="undefined"/>
  <description>WindowsExecutable</description>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
      <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
  </application>
</assembly>
```

staxrip:
https://raw.githubusercontent.com/staxrip/staxrip/master/My%20Project/app.manifest

mkvtoolnix:
https://gitlab.com/mbunkus/mkvtoolnix/-/raw/main/src/extract/manifest.xml.erb

mpv:
https://raw.githubusercontent.com/mpv-player/mpv/master/osdep/mpv.exe.manifest

mpv.net:
https://raw.githubusercontent.com/stax76/mpv.net/master/mpv.net/app.manifest
