### ISSUE TITLE
cargo-c v0.7.1+cargo-0.49: compiling fails (de.rs:530:63 - type annotations needed)

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1905]
[cargo-c issue 159](https://github.com/lu-zero/cargo-c/issues/159) - suggested workaround: `cargo install cargo-c --locked`

[ab-suite.rust.install.log](https://github.com/lu-zero/cargo-c/files/5866699/ab-suite.rust.install.log)

----

PS: [cargo issue 9101](https://github.com/rust-lang/cargo/issues/9101) - may get fixed upstream soonish

**Comment by HunterAP23** [comment]
Not sure that posting an issue due to an external dependency of a dependency is broken, but sure.
I tried running `cargo install cargo-c --locked` in the mintty environment but a different error came up.

You can still build FFmpeg but you need to explicitly disable the building `aom`, `rav1e1`,  `dav1d`, and `libavif=2` in `build/media-autobuild_suite.ini` and `build/ffmpeg_options.txt`. The names are different in in the `build/ffmpeg_options.txt` file, so here's how they map out:

`library` | `media-autobuild_suite.ini` | `ffmpeg_options.txt`
`aom` | set `aom=2` | change `--enable-libaom` to `--disable-libaom`
`dav1d` | set `dav1d=2` | change `--enable-libdav1d` to `--disable-libdav1d`
`rav1e` | set `rav1e=2` | change `--enable-librav1e` to `--disable-librav1e`
`avif` | set `libavif=2` | No changes needed

Then retry the build and `cargo-c` won't be a problem since it's only used to build the above libraries.

**Comment by LigH-de** [comment]
I mainly posted it to report that I already investigated a bit about the reason, and it is not the fault of the suite... so the main solution (if you want to build anything that depends on rust) is "patience".

**Comment by LigH-de** [comment]
May it be suitable to temporarily lock down the cargo version until this issue is solved?

**Comment by LigH-de** [comment]
Solved.
