### ISSUE TITLE
Build mpv from master [question]

### ISSUE THREAD

**Issue by Doofussy2** [m-ab-s/media-autobuild_suite#1968]
I have just got everything installed and appears to be working correctly. The suite is building v0.33 and not even v0.33.1. I would like to build mpv from master, but I am a total noob, and can't figure out how to do this. I imagine I need to clone the repo, but how do I add that to the build? I appreciate your help.

**Comment by 1480c1** [comment]
I'm not sure if I understand your question, we already build mpv from their git master branch, have you made sure you have mpv enabled and also rebuilt recently?

**Comment by Doofussy2** [comment]
Thanks for the response. I built the suite, today. The version that the suite built, is this:

mpv 0.33.0-138-g39630dc8b6 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat May  1 16:32:08 PDT 2021
FFmpeg library versions:
   libavutil       57.0.100
   libavcodec      59.0.100
   libavformat     59.0.100
   libswscale      6.0.100
   libavfilter     8.0.101
   libswresample   4.0.100
FFmpeg version: N-102195-gfc5b0c59c0-gc7c138e411+3

**Comment by 1480c1** [comment]
The build you have is https://github.com/mpv-player/mpv/commit/39630dc8b6 which was commited 6h ago and is the latest commit on their master branch, the reason why you don't see 0.33.1 is because that's a patch with fixes on top of their 0.33.0 branch which their master branch has already diverted from, so when the version script goes through the history to find the nearest tag, it only finds 0.33.0 since that was in the linear history.

**Comment by 1480c1** [comment]
This commit https://github.com/mpv-player/mpv/commit/b5d3e43198b9d57af5620b63537885aaa41fa8cd that 0.33.1 is tagged from is nowhere present on their master branch's linear history, part of the content might be in the form of patches that were back ported to 0.33.0, but the master branch will not contain 0.33.1

**Comment by Doofussy2** [comment]
Oh, well that's good to know. Thank you for the explanation. I guess that means you can close this.

**Comment by wiiaboo** [comment]
You can close it too, as the issue author.
