### ISSUE TITLE
Use python 3.9.5 when building vapoursynth R53 ?

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#1976]
Hello.  I wonder if you could please advance vapoursynth building of  R53 to use python portable 3.9.5 ?
vapoursynth R53 was built for python 3.9 ...
Thanks !

**Comment by Biswa96** [comment]
Python 3.9 is hell of a work https://github.com/msys2/MINGW-packages/pull/8278

**Comment by 1480c1** [comment]
One issue with python 3.9.5 that I know of right now is that it doesn't run on Windows 7 out of the box, so that might be an issue for us, but then again I guess technically, the "official" stance of mabs on Windows 7 is that it's not supported since Microsoft doesn't officially support it for the general public, but I guess we don't really intend to forcefully break Windows 7 builds, at least atm and will probably just let it naturally break as newer packages might require newer things not available to Windows 7.

**Comment by hydra3333** [comment]
thay sounds like a plan.
