### ISSUE TITLE
(not an issue) what version did I just compile?

### ISSUE THREAD

**Issue by illtellyoulater** [m-ab-s/media-autobuild_suite#2099]
Hello, I have a kind of a naive question... I just built FFmpeg for the first time using media-autobuild suite, and when I lauch it it shows:

> ffmpeg version N-105207-ga5125325bc-g24b93022fe+1 Copyright (c) 2000-2022 the FFmpeg developers

From this line, how do I make sense of which FFmpeg version I just compiled? For example, is it FFmpeg 4.4.1 or 5.0?
Or does it mean I compiled the very latest (current) FFmpeg repository status? 
If so, how can I determine, from that _version_ string (N-105207-ga5....), the date-time of the FFmpeg repository used in my build?
Thanks!

**Comment by 1480c1** [comment]
So looking at the version string bit by bit

> ffmpeg version 

normal

> N-

not a tag

> 105207

105207 commits since root (meaning 105207 commits since the project's existance)

> ga5125325bc

`g` + the resulting hash of the overall repo (the `a5125325bc` part)

> g24b93022fe

`g` + the commit hash of the repo as it was pulled (https://github.com/FFmpeg/FFmpeg/commit/24b93022fe)

> +1

One patch was added on top of the repo after it was pulled

> the date-time of the FFmpeg repository 

As far as I know, unless it shows up on the creation date or the "birth" date of it when using `stat` on it, but that often doesn't actually correlate to the actual time it was compiled, only the time it appeared on the file system.

Although theoretically, there is a way by using the `.gnu.build-id` tag on Linux and other systems that use the ELF format by literally doing a birthday attack by compiling ffmpeg over and over and changing the `SOURCE_DATE_EPOCH` env variable and doing so until the sha1 hash stored in the build-id manages to collide, but such a thing doesn't exist on Windows.


Any other questions?

**Comment by illtellyoulater** [comment]
Wow, thanks for the very detailed answer! No other questions sir! :)
