### ISSUE TITLE
openmpt: undefined reference to off and vorbis symbols

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2168]
13:08:47 ┌ openmpt git  .............................. [Recently updated]
13:08:48 ├ Running clean...
13:08:55 ├ Running install...
Likely error (tail of the failed operation logfile):
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3709): undefined reference to `ogg_stream_reset_serialno'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x373e): undefined reference to `ogg_stream_packetout'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3775): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3879): undefined reference to `vorbis_synthesis_halfrate'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x408c): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x41cc): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x41e2): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x208a): undefined reference to `vorbis_synthesis_halfrate_p'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:1734: bin/libopenmpt.dll] Error 1
 [logs.zip](https://0x0.st/obDg.zip)

**Comment by deepakmohandasan** [comment]
I'm also facing the same issue, have you found any fixes for this ?

**Comment by 1480c1** [comment]
I have not been able to reproduce this with the .ini and config.txt files provided in the original post, so I do not have a way to reproduce and verify this

Could you guys also provide your logs.zip files?

**Comment by deepakmohandasan** [comment]
Attaching the logs.zip file and openmpt install log
[openmpt-ab-suite.install.log](https://github.com/m-ab-s/media-autobuild_suite/files/8549478/openmpt-ab-suite.install.log)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8549479/logs.zip)

**Comment by Nekofoxmiu** [comment]
same here

┌ openmpt git  ........................................ [Recently updated]
├ Running clean...
├ Running install...
Likely error (tail of the failed operation logfile):
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3709): undefined reference to `ogg_stream_reset_serialno'
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x373e): undefined reference to `ogg_stream_packetout'
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3775): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3879): undefined reference to `vorbis_synthesis_halfrate'
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x408c): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x41cc): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x41e2): undefined reference to `vorbis_synthesis_halfrate_p'
C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x208a): undefined reference to `vorbis_synthesis_halfrate_p'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:1746: bin/libopenmpt.dll] Error 1
install failed. Check C:/ffmpeg_wow/build/openmpt-git/ab-suite.install.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oTJf.zip
Copy and paste [logs.zip](https://0x0.st/oTJf.zip) in the GitHub issue.


I think that is because 

\build\openmpt-git\include\vorbis\include\vorbis\[need .h file] is in wrong place.

in error message it should in \build\openmpt-git\include\vorbis

**Comment by Nawor3565** [comment]
> same here
> 
> ┌ openmpt git ........................................ [Recently updated] ├ Running clean... ├ Running install... Likely error (tail of the failed operation logfile): C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3709): undefined reference to `ogg_stream_reset_serialno' C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x373e): undefined reference to `ogg_stream_packetout' C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3775): undefined reference to `vorbis_synthesis_halfrate_p' C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x3879): undefined reference to `vorbis_synthesis_halfrate' C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x408c): undefined reference to `vorbis_synthesis_halfrate_p' C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x41cc): undefined reference to `vorbis_synthesis_halfrate_p' C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x41e2): undefined reference to `vorbis_synthesis_halfrate_p' C:/ffmpeg_wow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg_wow/msys64/mingw64/lib/../lib/libvorbisfile.a(vorbisfile.o):(.text+0x208a): undefined reference to `vorbis_synthesis_halfrate_p' collect2.exe: error: ld returned 1 exit status make: *** [Makefile:1746: bin/libopenmpt.dll] Error 1 install failed. Check C:/ffmpeg_wow/build/openmpt-git/ab-suite.install.log This is required for other packages, so this script will exit. Creating diagnostics file...
> 
> All relevant logs have been anonymously uploaded to https://0x0.st/oTJf.zip Copy and paste [logs.zip](https://0x0.st/oTJf.zip) in the GitHub issue.
> 
> I think that is because
> 
> \build\openmpt-git\include\vorbis\include\vorbis\ [need .h file] is in wrong place.
> 
> in error message it should in \build\openmpt-git\include\vorbis

> 

Can confirm this was the issue, moving those .h files to the proper directory fixed the problem.
