### ISSUE TITLE
Failing to build libwebp

### ISSUE THREAD

**Issue by Katzenwerfer** [m-ab-s/media-autobuild_suite#2188]
[logs.zip](https://0x0.st/omiI.zip)
```
01:16:09 ┌ libwebp git  .............................. [Recently updated]
0006-CMake-add-WEBP_BUILD_WEBPINFO-to-list-of-checks-for-.patch
        Patch could not be applied with `git am`. Continuing without patching.
01:16:14 ├ Running cmake...
01:16:28 ├ Running build...
Likely error (tail of the failed operation logfile):
[8/10] Linking C static library libwebpmux.a
[9/10] Building C object CMakeFiles/webpinfo.dir/examples/webpinfo.c.o
FAILED: CMakeFiles/webpinfo.dir/examples/webpinfo.c.o
C:\KatC\media-autobuild\msys64\mingw64\bin\ccache.exe  gcc -DHAVE_CONFIG_H -DUNICODE -DWEBP_SWAP_16BIT_CSP=1 -D_UNICODE -IC:/KatC/media-autobuild/msys64/mingw64/include -IC:/KatC/media-autobuild/build/libwebp-git/build-64bit/src -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG   -Wall -MD -MT CMakeFiles/webpinfo.dir/examples/webpinfo.c.o -MF CMakeFiles\webpinfo.dir\examples\webpinfo.c.o.d -o CMakeFiles/webpinfo.dir/examples/webpinfo.c.o -c C:/KatC/media-autobuild/build/libwebp-git/examples/webpinfo.c
In file included from C:/KatC/media-autobuild/build/libwebp-git/examples/webpinfo.c:22:
C:/KatC/media-autobuild/build/libwebp-git/imageio/imageio_util.h:17:10: fatal error: webp/types.h: No such file or directory
   17 | #include "webp/types.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check C:/KatC/media-autobuild/build/libwebp-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
```

**Comment by rafnunes777** [comment]
Same here 
[https://0x0.st/omp-.zip]

**Comment by Barough** [comment]
libwebp builds fine here except for the known patch 'issue'.

**Comment by LigH-de** [comment]
Works here too.

**Comment by Katzenwerfer** [comment]
Apparently, it only occurs if you build without standalone binaries from FFmpeg (which doesn't really makes much sense). I still need to test it out to confirm it.

**Comment by hunterhogan** [comment]
[logs.zip](https://0x0.st/oa_R.zip)

Same error. I had selected "build without standalone binaries." 

I see,

> I still need to test it out to confirm it.

So, in C:\mabs\build\media-autobuild_suite.ini I have changed `standalone=2` to `standalone=1`, and I started the build process again by double-clicking C:\mabs\media-autobuild_suite.bat from Windows Explorer. 

The cmd window opened, quickly cast its spells, and closed. Mintty opened as expected, but the first two lines are

> Error: Could not open log file: File exists.
> C:\mabs\build\compile.log.

I have run media-autobuild_suite.bat about 20 times in the last few months on an antique computer. I ran it that many times because the build kept failing at different points. While I certainly did not read the first two lines of Mintty when Mintty re-leaunched after media-autobuild_suite.bat updated Msys2 and updated itself, this is the first time I have seen that specific error. I don't know how "Could not open log file: File exists." could possibly be related to the webp problem, but I'm trying to be thorough in my description of the troubleshooting process. I noticed that I still had the old instance of Mintty open (the instance that produced the attached error logs) this entire time. I just closed that instance.

The new instance produced a couple of interesting things:

> 11:37:59 Warning: We will not accept any issues lacking any form of logs or logs.zip!
> 11:37:59
>         Starting 64bit compilation of all tools
> Imported default FFmpeg options from .bat
> License: nonfree
> Imported default mpv options from .bat
> 11:38:15
>         Starting 64bit compilation of global tools
> 11:38:15 ├ Running rustup_update...
> 11:38:16 ├ Running set_default_toolchain...
> 11:38:18   Running git update for ripgrep...
> 11:38:18 ripgrep git  ...................................... [Up-to-date]
> 11:38:20   Running git update for jo...
> 11:38:20 jo git  ........................................... [Up-to-date]
> 11:38:22   Running git update for jq...
> 11:38:22 jq git  ........................................... [Up-to-date]
> 11:38:24   Running git update for dssim...
> 11:38:24 dssim git  ........................................ [Up-to-date]
> 11:38:27   Running git update for libxml2...
> 11:38:27 libxml2 git  ...................................... [Up-to-date]
> 11:38:33   Running git update for freetype...
> 11:38:34 freetype git  ..................................... [Up-to-date]
> 11:38:35   Running git update for fontconfig...
> 11:38:35 fontconfig git  ................................... [Up-to-date]
> 11:38:38   Running git update for harfbuzz...
> 11:38:39 harfbuzz git  ..................................... [Up-to-date]
> 11:38:40   Running git update for fribidi...
> 11:38:40 ┌ fribidi git  ................................. [Files missing]
> 11:38:41 ├ Running meson...
> 11:38:44 ├ Running build...
> 11:38:52 ├ Running install...
> 11:38:52 ├ Stripping...
> 11:38:52 └ fribidi-git  ....................................... [Updated]
> 11:38:54   Running git update for libass...
> 11:38:55 ┌ libass git  ............................. [Newer dependencies]
> 11:38:55 ├ Running autoreconf...
> 11:39:16 ├ Running uninstall...
> 11:39:16 ├ Running configure...
> 11:39:43 ├ Running make...
> 11:39:58 ├ Running install...
> 11:39:59 ├ Stripping...
> 11:39:59 └ libass-git  ........................................ [Updated]
> 11:40:00 gnutls 3.6.16  .................................... [Up-to-date]
> 11:40:02 libidn2 2.3.0  ................................. [Files missing]
> 11:40:02 ├ libidn2-2.3.0  ............................. [File up-to-date]
> 11:40:02 ├ Running extract...
> 11:40:04 ├ Running uninstall...
> 11:40:04 ├ Running configure...
> 11:41:51 ├ Running make...
> 11:42:29 ├ Running install...
> 11:42:32 ├ Stripping...
> 11:42:33 └ libidn2-2.3.0  ..................................... [Updated]
> 11:42:33 libpsl 0.21.0  ............................ [Newer dependencies]
> 11:42:33 ├ libpsl-0.21.0  ............................. [File up-to-date]
> 11:42:33 ├ Running extract...
> 11:42:35 ├ Running uninstall...
> 11:42:35 ├ Running configure...
> 11:43:10 ├ Running make...
> 11:43:19 ├ Running install...
> 11:43:21 ├ Stripping...
> 11:43:21 └ libpsl-0.21.0  ..................................... [Updated]
> 11:43:25   Running git update for curl...
> 11:43:25 curl git  ......................................... [Up-to-date]
> 11:43:27   Running git update for freeglut...
> 11:43:27 freeglut git  ..................................... [Up-to-date]
> 11:43:30   Running git update for libtiff...
> 11:43:30 libtiff git  ...................................... [Up-to-date]
> 11:43:32   Running git update for libwebp...
> 11:43:32 ┌ libwebp git  .............................. [Recently updated]
> 0006-CMake-add-WEBP_BUILD_WEBPINFO-to-list-of-checks-for-.patch
>         Patch could not be applied with `git am`. Continuing without patching.
> 11:43:36 ├ Running cmake...
> 11:43:44 ├ Running build...
> 11:43:59 ├ Running install...
> 11:44:00 ├ Stripping...
> 11:44:00 └ libwebp-git  ....................................... [Updated]
> 11:44:01   Running git clone for leptonica...
> 11:44:07 ┌ leptonica git  ............................ [Recently updated]
> 11:44:07 ├ Running autogen...
> 11:44:20 ├ Running configure...
> 11:45:08 ├ Running make...
> 11:46:20 ├ Running install...
> 11:46:22 ├ /local64/lib/liblept.a  .......................... [Not found]
> 11:46:22 └ leptonica-git  ...................................... [Failed]
> 
> Try deleting '/build/leptonica-git' and start the script again.
> If you are sure there are no dependencies, <Enter> to continue building.
> Close this window if you wish to stop building.

In Mintty, I selected the text above and typed ctrl+c. Mintty instantly closed. I don't think I fat-fingered the ctrl+c, _but_ it is 11:46 AM UTC, which is 6:46 AM in my chair. And sitting in my chair is a tired, old man who hasn't had breakfast or coffee yet. Therefore, it is entirely possible that I fat-fingered or even fat-fisted the keyboard after successfully typing ctrl+c. (We know it was successful because ctrl+v worked as expected.) 

I'm back in Windows Explorer. It tells me that update_suite.sh was last modified about the time that I last started media-autobuild_suite.bat. That's the expected behavior, right? Relevant? IDK. Useful? IDK.

![Troubleshooting screenshot](https://user-images.githubusercontent.com/2958419/169650719-cec410dc-68cb-4e32-bab5-8a62b5c422d0.png)

I double-click media-autobuild_suite.bat. CMD opens for a short time. Mintty opens and closes and opens. "Error: Could not open log file: File exists." is _not_ present this time, sooooooo that was PEBCAK. (I could just delete that part: I haven't submitted these notes yet. Meh, whatever. Momma always told me, "PEBCAK is as PEBCAK does.")

Last time, Mintty paused at leptonica to wait for user input. This time, no other instances of Mintty were open, and it didn't pause. I also decided not to copy-paste from Mintty, so here is Paint's interpretation of the installation process. 

![Probably more evidence of PEBACK](https://user-images.githubusercontent.com/2958419/169651020-fabd55f8-e4b9-4aba-88fb-2bc21f0849c5.png)

I hope this is not more PEBCAK, but it probably is. 

Mintty git code. Man git coffee.

**Comment by hunterhogan** [comment]
You probably already figured out that I know some things about some things, but very few things about git and make. The latest error is too far beyond my understanding for me to even guess what additional information would be useful to you. :/

So, [logs.zip](https://0x0.st/oaLD.zip).


FYI, but you probably already know this: in Mintty, I selected `[logs.zip](https://0x0.st/oaLD.zip)` and typed ctrl+c. This time, I am confident I did not accidentally enter other keystrokes.[^1] Nevertheless, Mintty closed. In similar situations, if I selected text, right-clicked, and selected copy, Mintty did not close. 


[^1]: I do, in fact, unintentionally enter keystrokes much more frequently than the average of the user population and much more often in the last year than during the rest of my life. Therefore, in my first comment, I was serious about the possibility that I hit other keys without realizing it.

**Comment by LigH-de** [comment]
Ctrl+C interrupts. Use Ctrl+Ins instead, or click through the menu.

I knew the alternative key combos, as they were used in Borland's Turbo Vision IDE of their DOS compilers (e.g. Turbo Pascal 5), already before I learned the WordStar based ones, when I later used Turbo Pascal 3 for CP/M on a home computer which did not provide an Ins key, during computer classes in my school.

Ctrl+C ~ Ctrl+Ins
Ctrl+V ~ Shift+Ins

**Comment by hunterhogan** [comment]
I tried to post the following information nine days ago, but GitHub said "You cannot comment at this time." I hope GitHub will now let me tell you that I resolved the problem on my system and tell you how I resolved it.

## Rejected comment from 21 May 2022

> 05:10:49 Compilation successful.

[logs.zip](https://0x0.st/oaOa.zip)
[logs.zip](https://0x0.st/oaVe.zip)
[build.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8800172/build.zip)

### Timeline highlights

1. "FAILED: CMakeFiles/webpinfo.dir/examples/webpinfo.c.o"
2. In media-autobuild_suite.ini, change to `standalone=1` and `autouploadlogs=1`
3. "11:44:00 └ libwebp-git ....................................... [Updated]"
4. "ERROR: libjxl >= 0.7.0 not found using pkg-config"
5. In media-autobuild_suite.ini, change to `standalone=2` 
6. Same error.
7. In media-autobuild_suite.ini, change to `ffmpegChoice=1`
8. In ffmpeg_options.txt, change to `#--enable-libjxl` and `--enable-liblensfun`
9. "Compilation successful."

### Observations 

1. I, the user, changed only a few options, so that may help isolate the problems.
2. I paid close attention to the mabs repo through Github Desktop. There were no commits to mabs during the troubleshooting process. 
3. I did not resolve the libjxl error: I excluded libjxl from the build.
4. _Something_ resolved the webp error. Once the error was resolved, it never returned. I made _exactly_ two changes before the error was resolved:  `standalone=1` and `autouploadlogs=1`
5. Keeping in mind that I am largely ignorant about git and many other things happening "under the hood" of mabs, I speculate that the _results_ of the libwebp-git process were affected by the difference between `standalone=2` and `standalone=1`. I am not speculating whether the difference was on the client end (mabs) or the server end (libwebp repo). However, I suggest that when `standalone=2`, one or more necessary files were not cloned to my computer, which resulted in the compile error. After changing to `standalone=1`, all of the necessary files were cloned to my computer and remained in the cache for all of the other attempts to build FFmpeg, which is why the webp compile error never returned. 
6. I speculate that the webp and libjxl are unrelated.

### Thank you

Good luck! And, thank you very much for creating and maintaining this complicated script. Without the script, I would certainly not be able to compile a custom FFmpeg that was worth compiling.

**Comment by 1480c1** [comment]
Right now working on getting a chain of patches upstreamed at https://chromium-review.googlesource.com/c/webm/libwebp/+/3681983

**Comment by Patrick12300** [comment]
Same here.

[ab-suite.build.log](https://github.com/user-attachments/files/21582470/ab-suite.build.log)
