### ISSUE TITLE
Request: Apply unmerged yt-dlp patches (continuously updated)

### ISSUE THREAD

**Issue by ultrasound1372** [m-ab-s/media-autobuild_suite#2210]
FFmpeg apparently is missing a few features on Windows, the most noticeable being long path support. [This repo](https://github.com/yt-dlp/FFmpeg-builds) seems to fix that and the custom patch application works, but I'm running into a bit of a snag. That repo is continuously updated, presumably to keep up to date with changes on master. When these updates happen it is quite possible for the URLs to the .patch files to change. While I can use raw links to a specific commit which works, this possibly puts me behind.  
I do not know enough about the environment to create a ffmpeg_extra that would ensure this repo is up to date and then apply the patch files contained within to FFmpeg. They also have patches for AOM but I'm unsure if those are necessary, and I don't personally use them.  
My request therefore is either to integrate this set of patches into the suite for the time being, likely until they're merged upstream, or to help me do so on my local suite. The WIKI does not give enough info to manage a dynamic workflow like this one. Is there a version of the patch function in the helper script that could be used for this kind of thing, pulling patches from a git repository rather than something static?

**Comment by 1480c1** [comment]
If you need a constantly updated url, you can use <https://github.com/BtbN/FFmpeg-Builds/compare/master...yt-dlp:master.patch>

**Comment by 1480c1** [comment]
wait, nvm, that's not a FFmpeg fork

**Comment by 1480c1** [comment]
It seems @softworkz is already working on getting long path support upstreamed to FFmpeg in some of his patches, however, it seems his patches so far lack some other stuff done in the patches mentioned in that repo such as the MAX_PATH limitations

**Comment by softworkz** [comment]
The patches have been applied yesterday and today.
Those other patches are still a WIP, but actually those don't really matter for real-world situations.

**Comment by ultrasound1372** [comment]
> Those other patches are still a WIP, but actually those don't really matter for real-world situations.
If `MAX_PATH` is only 260, those do matter for real-world situations I believe, unless the values are just not used. I use the FFmpeg I build to interface with yt-dlp among other things, so I only need the one in my path. Given that I often need to do things like time/duration stamp the videos I download which are lower in a directory tree I do need support for this to be guaranteed. And when you say they're applied, do you mean they're applied to some fork of yours or that they've been brought upstream?

**Comment by softworkz** [comment]
> > Those other patches are still a WIP, but actually those don't really matter for real-world situations.
> 
> If `MAX_PATH` is only 260, those do matter for real-world situations I believe,

Those MAX_PATH patches are about solving these three very specific cases **only**:

1. Using ffmpeg with AviSynth
   when the input/import script to AviSynth is located on a path with len > 1040 (4 * MAX_PATH is supported already)
  the submitted patch will remove that limit (it's specific to AviSynth only)
2.  When ffmpeg.exe (itself) is located on a long path AND you are using presets in a subfolder `./ffpresets` 
  that doesn't work and will be fixed by one of those patches
3.  ffmpeg needs to load a dll from a long path
  practically a non-issue, because no dll that ffmpeg will ever load is on a long path location

For all other cases:  ffmpeg does not use fixed-size strings anywhere for accessing files. There is no MAX_PATH limitation for any case excepting these three above.

State of today, you can use ffmpeg with long paths everywhere, on all Windows versions, and without needing to make any registry changes for long path support. It will just work.

**Comment by 1480c1** [comment]
Due to https://github.com/yt-dlp/FFmpeg-Builds/commit/bcc023056b9a265304b32ff9fab34e3d6b192a67

I think this issue can be closed
