### ISSUE TITLE
can not build rav1e

### ISSUE THREAD

**Issue by forthyen** [m-ab-s/media-autobuild_suite#2217]
Likely error (tail of the failed operation logfile):
          D:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\media-autobuild_suite\build\rav1e-git\target\x86_64-pc-windows-gnu\release\deps\rav1e-91d1536728dd5b63.4ql981d8j2443t16.rcgu.o: in function `once_cell::sync::OnceCell<T>::get_or_try_init':
          D:/media-autobuild_suite/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\once_cell-1.12.0\src/lib.rs:1063: undefined reference to `__imp__ZN15crossbeam_epoch7default9COLLECTOR17ha85cf7255fe8d9bbE'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `rav1e` (bin "rav1e") generated 1 warning
error: could not compile `rav1e` due to previous error; 1 warning emitted
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8934779/logs.zip)

**Comment by Barough** [comment]
Same issue here

┌ rav1e git  .......................................... [Recently updated]
├ Running uninstall...
├ Running rust.update...
├ Running rust.build...
Likely error (tail of the failed operation logfile):
  = note: D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: D:\MABS-ffmpeg\build\rav1e-git\target\i686-pc-windows-gnu\release\deps\rav1e-affd16ae83efd9b8.m9nagorp0xovcxe.rcgu.o: in function `ZN15crossbeam_epoch7default11with_handle17ha1ae67252071fce7E':
          D:/MABS-ffmpeg/msys64/opt/cargo\registry\src\github.com-1285ae84e5963aae\crossbeam-epoch-0.9.9\src/internal.rs:(.text+0x30b): undefined reference to `_imp___ZN15crossbeam_epoch7default9COLLECTOR17hd32c8f6291a208e5E'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `rav1e` (bin "rav1e") generated 1 warning
error: could not compile `rav1e` due to previous error; 1 warning emitted
rust.build failed. Check D:/MABS-ffmpeg/build/rav1e-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ouxz.zip

**Comment by 1480c1** [comment]
Maybe related to https://github.com/crossbeam-rs/crossbeam/commit/08e41e184832f9d0bd49d97e21be1d60c437a894 ?

**Comment by korhan91** [comment]
Hello, I had this issue today as well:

```
  Running git update for rav1e...
┌ rav1e git  .......................................... [Recently updated]
├ Running rust.update...
├ Running rust.build...
Likely error (tail of the failed operation logfile):
          D:/ab_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\ab_suite\build\rav1e-git\target\x86_64-pc-windows-gnu\release\deps\rav1e-068e5f43ece944f4.38o7fveeuhj9z79y.rcgu.o: in function `once_cell::sync::OnceCell<T>::get_or_try_init':
          D:/ab_suite/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\once_cell-1.12.0\src/lib.rs:1063: undefined reference to `__imp__ZN15crossbeam_epoch7default9COLLECTOR17h8e781dd9ada53e42E'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `rav1e` (bin "rav1e") generated 1 warning
error: could not compile `rav1e` due to previous error; 1 warning emitted
rust.build failed. Check D:/ab_suite/build/rav1e-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oS93.zip
Copy and paste [logs.zip](https://0x0.st/oS93.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```
[logs.zip](https://0x0.st/oS93.zip)

**Comment by somogpt1** [comment]
+1

A domingo, 26/06/2022, 13:25, korhan91 ***@***.***> escreveu:

**Comment by Barough** [comment]
Don't really know how to best describe the issue in question over at [crossbeam](https://github.com/crossbeam-rs/crossbeam) and make a bug report....... any suggestion?

**Comment by 1480c1** [comment]
pushed https://github.com/m-ab-s/media-autobuild_suite/commit/85fc88b, upstream issue https://github.com/crossbeam-rs/crossbeam/issues/856 was closed as an "upstream issue" for rust itself.

**Comment by Barough** [comment]
Thnx for the fix. Working now. :)
