### ISSUE TITLE
[mingw64] [opus-tools] undefined reference to `SSL_connect'

### ISSUE THREAD

**Issue by 32-bit-link** [m-ab-s/media-autobuild_suite#2297]
``` bash
08:57:20 ┌ opus-tools git  ......................... [Newer dependencies]
08:57:20 ├ Running autogen...
08:58:26 ├ Running configure...
09:00:02 ├ Running make...
Likely error (tail of the failed operation logfile):
D:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/mabs/msys64/mingw64/lib/libopusurl.a(libopusurl_la-http.o):(.rdata$.refptr.SSL_connect[.refptr.SSL_connect]+0x0): undefined reference to `SSL_connect'
D:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/mabs/msys64/mingw64/lib/libopus.a(bands.o):(.text+0x3f01): undefined reference to `__memcpy_chk'
D:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/mabs/msys64/mingw64/lib/libopus.a(PLC.o):(.text+0x2ee): undefined reference to `__memcpy_chk'
D:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/mabs/msys64/mingw64/lib/libopus.a(decode_core.o):(.text+0x291): undefined reference to `__memcpy_chk'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:670: opusdec.exe] Error 1
make[2]: Leaving directory '/build/opus-tools-git/build-64bit'
make[1]: *** [Makefile:1111: all-recursive] Error 1
make[1]: Leaving directory '/build/opus-tools-git/build-64bit'
make: *** [Makefile:531: all] Error 2
make failed. Check D:/mabs/build/opus-tools-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
09:00:19   Creating diagnostics file...
```

[logs.zip](https://0x0.st/o4FU.zip)

**Comment by RivenSkaye** [comment]
This is caused by a change upstream that, in certain edge cases, seems to not use `-fstack-protector` or `-lssp` in the opus-tools package. It sets `-fstack-protector-strong` conditionally and I'm _trying_ to figure out what to change to make it work again atm

**Comment by nikolasr** [comment]
Thanks a lot!!
Changing line 819 of `media-suite_compile.sh` from 
`do_separate_confmakeinstall audio` 
to 
`do_separate_confmakeinstall audio LDFLAGS="$LDFLAGS -fstack-protector -lssp"`
seems to work for me, without changing `_FORTIFIY_source=2`

**Comment by 1480c1** [comment]
I guess perhaps I should consider relooking into adding `-fstack-protector-strong` in LDFLAGS globally, main issue will probably be performance, since I don't have any data for Windows

**Comment by coribald** [comment]
> Thanks a lot!! Changing line 819 of `media-suite_compile.sh` from `do_separate_confmakeinstall audio` to `do_separate_confmakeinstall audio LDFLAGS="$LDFLAGS -fstack-protector -lssp"` seems to work for me, without changing `_FORTIFY_source=2`

thanks for this suggestion! worked for me too.

**Comment by RivenSkaye** [comment]
> I guess perhaps I should consider relooking into adding `-fstack-protector-strong` in LDFLAGS globally, main issue will probably be performance, since I don't have any data for Windows

It would satisfy some of the conditional checks that make opus-tools set `_FORTIFY_SOURCE`, but I don't think a performance penalty would be worth it, most notably with the video codecs in mind. Setting it globally for audio doesn't seem like too bad an idea, but imo the best bet would be to look at patches in the collection repo for all packages that seem to depend on it, leaving it out of those that build and run fine without it.
Been having some issues building and linking with some other unholy combinations too, so looking into ways to fix those as I go as well. Depending on the changes I'll have to make, I might even opt to attempt a PR somewhere this or early next month to close a couple issues with.

**Comment by hydra3333** [comment]
so many dependencies, so much open source no user can be fully across, so many vulnerabilities, so many real-world hacks nowadays from "state actors" ... should perhaps 
"-fstack-protector-all" and "-D_FORTIFY_SOURCE=2" 
be defaults for all nowadays ?

yes yes performance vs security ... how much do you value your family's  personal information and money ?

**Comment by RivenSkaye** [comment]
Not sure if troll comment or misinformed user. But for anyone reading this comment section, it's about securely handling _memory and resources_, prevention of stackoverflows, not performing more memory copies than actually needed, not leaving some initialized memory dangling around without every freeing it, etc. This has nothing to do with a third party actor being able to listen or watch along.

That said, I've managed to get a fully functional build up until the part where I'm building and linking ffmpeg itself! Opus-tools (fixed w/ patch) and librtmp (just excluding for now) seem to be the only real issues in the build stack. That includes alternate upstreams for x264 and x265 and excludes all of CUDA because I'm running a double Red system.
That said, I'm having issues with pkg-config not being able to find a lot of stuff. Will try and wrangle scripts to get that working.

**Comment by 1480c1** [comment]
> It would satisfy some of the conditional checks that make opus-tools set `_FORTIFY_SOURCE`, but I don't think a performance penalty would be worth it, most notably with the video codecs in mind. Setting it globally for audio doesn't seem like too bad an idea

Personally, from a maintainer's side, it would be easier for me to just apply it globally and disable it selectively for individual packages that get a large enough performance hit to make it worth it. Plus, as @hydra3333 (probably not fully trolling) mentioned, for smaller libraries and packages that might not have as much scrutiny for security compared to the others, having `-fstack-protector-strong` on would probably bring more benefits than downsides in the long run. `-fstack-protector-all` would probably hit performance too hard though.


I did previously try adding `-fstack-protector-strong`, but since the issue it was supposed to address just disappeared, we never merged it.

Separately, the issue seems to be that even though we build our own opus, opusurl, opusfile etc, opus-tools is trying to link against msys2's provided mingw-w64-x86_64-libopus.

 I don't know if this is a pkg-config file issue or pkgconf issue or something else, as using msys2's packages (so not mabs'):
 ```bash
 $ pkgconf --static --libs opusurl
-LC:/msys64/ucrt64/lib -lssl -LC:/msys64/ucrt64/lib -lcrypto -lws2_32 -lgdi32 -lcrypt32 -lopusurl -lopusfile -LC:/msys64/ucrt64/lib -logg -lopus -lm -lssp
```

mabs:
```bash
$ pkgconf --static --libs opusurl
-LD:/mabs/msys64/mingw32/lib -lssl -LD:/mabs/msys64/mingw32/lib -lcrypto -lws2_32 -lgdi32 -lcrypt32 -LD:/mabs/local32/lib -lopusurl -lopusfile -LD:/mabs/local32/lib -logg -lopus -lm
```

linux install:
```bash
$ pkgconf --static --libs opusurl
-lopusurl -lopusfile -lm -logg -lopus -lm -lssl -ldl -pthread -lcrypto -ldl -pthread
```

somehow the order seems to be messed up regardless for windows

**Comment by 1480c1** [comment]
Forgot to mention in this issue

Opened an issue upstream about the ordering issue https://github.com/pkgconf/pkgconf/issues/268

**Comment by RivenSkaye** [comment]
There has been an update to pkgconf recently, but it starts failing elsewhere for different libs. Would it be an idea to move all of these pkgconf issues into a single tracking issue, rather than split like they are now?

**Comment by 1480c1** [comment]
Closed for now
