### ISSUE TITLE
Request: [mingw64] gnutls and python update request.

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#2311]
gnutls already released 3.7.8 and patch files need to update to suite the build.

Also Python 3.10.8 was released which suites the buiild.

**Comment by RivenSkaye** [comment]
[This patch](https://lists.gnupg.org/pipermail/gnutls-help/2022-September/004765.html) does not provide any changes relevant to earlier builds failing due to collisions with GnuTLS. It does address some bugs, all of which will error out earlier on with an incorrect configuration. I don't see any of it as an issue with mabs, but I don't see any need to bump the version either.

As for the Python patch, that'll probably come from uptream MSYS2 when it's built

**Comment by 1480c1** [comment]
Closed with https://github.com/m-ab-s/media-autobuild_suite/commit/2f648661c22293fd490828231158d700ca6169c6 and https://github.com/m-ab-s/media-autobuild_suite/commit/bdf992a602f33e70f092eb2489088d3f0db1f716
