### ISSUE TITLE
Multiple errors running make when git update for curl

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2353]
``` bash
00:27:58 libpsl 0.21.0  .................................... [Up-to-date]
00:28:10   Running git update for curl...
00:28:52 ┌ curl git  .................................... [Updates found]
00:28:54 ├ Running uninstall...
00:28:54 ├ Running autoreconf...
00:29:35 ├ Running configure...
00:33:47 ├ Running make...
Likely error (tail of the failed operation logfile):
  234 |   uint32_t error; /* HTTP/2 stream error code */
      |   ^~~~~~~~
../../lib/http.h:246:9: error: unknown type name 'uint8_t'
  246 |   const uint8_t *upload_mem; /* points to a buffer to read from */
      |         ^~~~~~~
make[2]: *** [Makefile:2107: libcurl_la-altsvc.lo] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/lib'
make[1]: *** [Makefile:1469: all] Error 2
make[1]: Leaving directory '/build/curl-git/build-64bit/lib'
make: *** [Makefile:1247: all-recursive] Error 1
make failed. Check C:/MinGW-w64/build/curl-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
00:33:53   Creating diagnostics file...
warning: database file for 'clangarm64' does not exist (use '-Sy' to download)
warning: database file for 'clangarm64' does not exist (use '-Sy' to download)

Attach C:\MinGW-w64\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10325552/logs.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/10325557/ab-suite.make.log)

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by andrerfcsantos** [comment]
Seeing the same problem:

- [logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10326702/logs.zip)
- [build/curl-git/build-64bit/ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/10326704/ab-suite.make.log)

**Comment by Mr-Z-2697** [comment]
Edit the curl git link in media-suite_compile.sh can bypass this, but I'm more interested in how can I just skip this step, building curl is unreasonably slow for god know reason

**Comment by Intrinsic27** [comment]
Just to confirm that i'm getting the same issue but without the 2 warnings after "00:33:53   Creating diagnostics file..."

**Comment by Intrinsic27** [comment]
> Edit the curl git link in media-suite_compile.sh can bypass this, but I'm more interested in how can I just skip this step, because building curl is unreasonably slow for god know reason.

You and edit the ini file in the build sub directory and set curl=2, i just did this and it built what i needed without errors.

**Comment by andrerfcsantos** [comment]
From what I gathered, the curl file that was throwing the error was "refactored" recently, along with other files (commit https://github.com/curl/curl/commit/71b7e0161032927cdfb4e75ea40f65b8898b3956). I'm assuming this is something to do with the error, but I'm no expert in C to pinpoint the reason why this caused the error.

So, what I tried to bypass this error was to fork curl, make the master branch of my fork to be the latest release (which is before that refactor) and set `media-suite_autocompile.sh` to point to my fork. So this:

https://github.com/m-ab-s/media-autobuild_suite/blob/29ab8ee544ba21b4a6625abf1089e45df97bdc1a/build/media-suite_compile.sh#L446-L447

became:

```bash
if [[ $mediainfo = y || $bmx = y || $curl != n || $cyanrip = y ]] &&
    do_vcs "https://github.com/andrerfcsantos/curl"; then
```

After doing this change curl compiled with no problems. 

I'm now having problems with the compilation of `rtmpdump`, but I think it's unrelated to this.

> You and edit the ini file in the build sub directory and set curl=2, i just did this and it built what i needed without errors.

Even with this, curl was still compiling, and after looking at the lines of `media-suite_compile.sh` posted above, I understand this option was not the only thing controlling if curl must be built. Since it seems I really need curl to compile, what worked for me was the workaround above.

**Comment by Mr-Z-2697** [comment]
I knew the ini file and being dependency of other tools sort of thing, I just wonder if we can just use pacman installed packages for this kind of "not very media related libraries".
Build these generic libraries to the latest git is not what I want to achieve with media-autobuild_suite.

**Comment by Biswa96** [comment]
Try with modifying the lib/http.h file in curl source directory like this

```diff
@@ -42,7 +42,7 @@ typedef enum {
 
 #ifndef CURL_DISABLE_HTTP
 
-#if defined(_WIN32) && defined(ENABLE_QUIC)
+#if defined(_WIN32)
 #include <stdint.h>
 #endif
 ```

I am not sure what the actual solution should be. This issue should be reported to upstream curl repository.

**Comment by 1480c1** [comment]
Fixed with https://github.com/curl/curl/commit/99327018cfae5fcf4ec75b7921383f4a5ee16e7f
