### ISSUE TITLE
first-time compilation fails -- SSL errors

### ISSUE THREAD

**Issue by stubhead** [m-ab-s/media-autobuild_suite#2605]
hello,

this is my first time trying to install MAS. when i execute media-autobuild_suite.bat, i get a stream of errors of the form :

	OpenSSL/3.2.0: error:0A0000C6:SSL routines::packet length too long

we're behind a firewall and use a proxy, so i thought that might be the problem, but windows' internet options on the machine are set to use the proxy correctly.  i also thought you might be using something like curl or wget to download the packages, so i made sure that http_proxy and https_proxy are also set.  nothing works.

i'm sending you a capture of the batch file output here attached, i hope it will give you an idea of what steps i can take to troubleshoot the install.
[log-capture.txt](https://github.com/m-ab-s/media-autobuild_suite/files/14334099/log-capture.txt)

in addition, here is some system information:
	O/S: Microsoft Windows Server 2019 Standard
	Version: 10.0.17763 N/A version 17763
	system type: x64-based PC
	Processor(s): 2 processor(s)
	[01] : Intel64 Family 6 Model 26 Stepping 5 GenuineIntel ~2128 MHz
	[02] : Intel64 Family 6 Model 26 Stepping 5 GenuineIntel ~1596 MHz
	Windows directory: C:\Windows
	system directory: C:\Windows\system32

any help/ideas appreciated !

thanks

**Comment by 1480c1** [comment]
Since the error is occurring in pacman, I think one thing you can try is to edit `/etc/pacman.conf` and uncomment the line that says `#XferCommand = /usr/bin/curl -L -C - -f -o %o %u`.

The issue probably stems from the fact that pacman has its own way of downloading packages by default, and so it will ignore your http(s)_proxy variables. I do not know how the rest of the suite will interact with being behind a proxy, so good luck
