### ISSUE TITLE
build fails, maybe because hard-coded ccache gcc and ccache g++

### ISSUE THREAD

**Issue by mojie126** [m-ab-s/media-autobuild_suite#2639]
Although the ccache setting is disabled, it is ignored in the script and is `hard-coded` into `ccache gcc` and `ccache g++` in many places.

In addition, I hope that proxy settings can be added. Chinese networks cannot access github smoothly.

Furthermore, some libraries have been installed in `/mingw64/lib`. I hope they can be corrected.

**Comment by L4cache** [comment]
> some libraries have been installed in /mingw64/lib

Which ones?

**Comment by L4cache** [comment]
> After reading the script, it was installed through pacman, such as libgsm, libcdio, etc.

That's expected behavior.

The `ccache` thing also didn't cause issue for, I guess, most if not all (other) m-ab-s users, if you can elaborate on what problem you have, for which package, we can be more helpful.

As for the proxy, I'm assuming that it's difficult to implement, there's environment variables for proxy in unix-like systems but I don't know if the msys2 is comply with those.
I'm Chinese too and I use proxifier to just proxy everything inside `C:\m-ab-s`.

**Comment by 1480c1** [comment]
ccache should be disabled by the line
```bash
[[ $ccache != y ]] && export CCACHE_DISABLE=1
```
which should tell `ccache` to just call the compiler without anything. If there is an issue due to command arg splitting or a build script looking for a program called `ccache gcc` etc, then we have the `gcc.bat` and `g++.bat` scripts (that's what we do with x265 `-DCMAKE_CXX_COMPILER="$LOCALDESTDIR/bin/${CXX#ccache }.bat"`)

For proxy stuff, there's not an easy way for the suite to handle that (since not everything accepts `https_proxy` on Windows). Your best option might be to edit `/local64/etc/custom_profile` to export the `http_proxy` and `https_proxy` variables. Alternatively, you can just set that as a global environment.


Without any logs, I can only consider this issue invalid as there's nothing for me to reproduce.
