### ISSUE TITLE
Hope to support msvc compilation

### ISSUE THREAD

**Issue by mojie126** [m-ab-s/media-autobuild_suite#2662]

**Comment by woot000** [comment]
Seems unlikely, but if anyone ever wanted to try giving it a shot, [this project](https://github.com/Data-Oriented-House/PortableBuildTools) may be a good starting point

**Comment by 1480c1** [comment]
MSVC compilation is out of scope for this project, plus it's not really a thing we can automate.

If you are looking for FFmpeg specifically, I would recommend <https://github.com/ShiftMediaProject/FFVS-Project-Generator> as I have used it before for work, and it worked pretty fine. Otherwise, you will need to consult the individual projects to see if they even support MSVC.
